# Generated by Django 2.2.24 on 2021-11-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospital_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Hospital_name', models.CharField(max_length=30)),
                ('Av_ICU_Beds', models.IntegerField()),
                ('Av_Normal_Beds', models.IntegerField()),
                ('Av_Oxygen_Cylinder', models.IntegerField()),
                ('City', models.CharField(max_length=30)),
                ('Locality', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Detail',
            fields=[
                ('Aadhar_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Birth_date', models.DateField()),
                ('Sex', models.CharField(max_length=1)),
                ('City', models.CharField(max_length=30)),
                ('Locality', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
                ('Email_ID', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Center',
            fields=[
                ('Center_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Center_name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Locality', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine_detail',
            fields=[
                ('Vaccine_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Vaccine_name', models.CharField(max_length=30)),
                ('Disease_targetting', models.CharField(max_length=30)),
                ('Required_Doses', models.IntegerField()),
                ('Interval_btw_Doses_indays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine_Consumer',
            fields=[
                ('Constumer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Vaccine_chosen', models.CharField(max_length=30)),
                ('Dose_completed', models.IntegerField()),
                ('Last_Dose_taken_date', models.DateField()),
                ('Aadhar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Personal_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Disease_Name', models.CharField(max_length=30)),
                ('Patient_Condition', models.CharField(max_length=30)),
                ('Registration_Date', models.DateField()),
                ('Aadhar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Personal_Detail')),
                ('Hospital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Center_Vaccine_reln',
            fields=[
                ('Relation_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Which_Dose', models.IntegerField()),
                ('Center_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Vaccination_Center')),
                ('Vaccine_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Vaccine_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_Num', models.IntegerField(primary_key=True, serialize=False)),
                ('Which_Dose', models.IntegerField()),
                ('Last_Dose_taken_date', models.DateField()),
                ('Date', models.DateField()),
                ('Slot_Time', models.DateField()),
                ('Aadhar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Personal_Detail')),
                ('Center_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Vaccination_Center')),
                ('Vaccine_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Vaccine_detail')),
            ],
        ),
    ]
