# Generated by Django 2.2.24 on 2021-11-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livlyf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine_consumer',
            name='Vaccine_chosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Vaccine_detail'),
        ),
    ]
