# Generated by Django 2.2.24 on 2021-11-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livlyf', '0002_auto_20211110_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine_Consumer',
        ),
    ]
