# Generated by Django 2.2.24 on 2021-11-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livlyf', '0003_delete_vaccine_consumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
