# Generated by Django 2.2.24 on 2021-11-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livlyf', '0004_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('Feedback', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='City',
            field=models.CharField(choices=[('Alwar', 'Alwar'), ('Mumbai', 'Mumbai')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Locality',
            field=models.CharField(choices=[('Kati Ghati', 'Kati Ghati'), ('Kala Kuan', 'Kala Kuan'), ('Ashoka Circle', 'Ashoka Circle')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Type',
            field=models.CharField(choices=[('General', 'General'), ('Male', 'Male'), ('Ladies', 'Ladies'), ('Children', 'Children')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Disease_Name',
            field=models.CharField(choices=[('COVID 19', 'COVID 19'), ('Cancer', 'Cancer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Patient_Condition',
            field=models.CharField(choices=[('Active', 'Active'), ('Recovering', 'Recovering'), ('Critical', 'Critical'), ('Dead', 'Dead')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vaccination_center',
            name='City',
            field=models.CharField(choices=[('Alwar', 'Alwar'), ('Mumbai', 'Mumbai')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vaccination_center',
            name='Locality',
            field=models.CharField(choices=[('Kati Ghati', 'Kati Ghati'), ('Kala Kuan', 'Kala Kuan'), ('Ashoka Circle', 'Ashoka Circle')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vaccine_detail',
            name='Disease_targetting',
            field=models.CharField(choices=[('COVID 19', 'COVID 19'), ('Cancer', 'Cancer')], max_length=30),
        ),
        migrations.CreateModel(
            name='Vaccine_Consumer',
            fields=[
                ('Constumer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Dose_completed', models.IntegerField()),
                ('Last_Dose_taken_date', models.DateField()),
                ('Aadhar_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Personal_Detail')),
                ('Vaccine_chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livlyf.Vaccine_detail')),
            ],
        ),
    ]
