# Generated by Django 2.2.24 on 2021-11-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livlyf', '0005_auto_20211114_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine_consumer',
            name='Aadhar_number',
        ),
        migrations.RemoveField(
            model_name='vaccine_consumer',
            name='Dose_completed',
        ),
        migrations.RemoveField(
            model_name='vaccine_consumer',
            name='Last_Dose_taken_date',
        ),
        migrations.RemoveField(
            model_name='vaccine_consumer',
            name='Vaccine_chosen',
        ),
    ]
