# Generated by Django 2.2.24 on 2021-11-14 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livlyf', '0007_auto_20211114_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_detail',
            name='Last_Dose_taken_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
