# Generated by Django 2.2.24 on 2021-11-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livlyf', '0009_auto_20211114_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine_Consumer',
        ),
    ]
